SweetsTreats/Models/Flavor.cs
using System.Collections.Generic;

namespace SweetsTreats.Models
{
    public class Flavor
    {
        public Flavor()
        {
            this.JoinEntities = new HashSet<FlavorTreat>();
        }

        public int FlavorId { get; set; }
        public string Name { get; set; }
        public virtual ApplicationUser User { get; set; }
        public virtual ICollection<FlavorTreat> JoinEntities { get;}
    }
}

SweetsTreats/Controllers/FlavorsController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using SweetsTreats.Models;
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using System.Threading.Tasks;
using System.Security.Claims;
using System.Collections.Generic;

namespace SweetsTreats.Controllers
{
  [Authorize]
  public class FlavorsController : Controller
  {
    private readonly SweetsTreatsContext _db;
    private readonly UserManager<ApplicationUser> _userManager;

    public FlavorsController(UserManager<ApplicationUser> userManager, SweetsTreatsContext db)
    {
      _userManager = userManager;
      _db = db;
    }

   [AllowAnonymous] 
   public ActionResult Index()
{
  List<Flavor> model = _db.Flavors.ToList();
  return View(model);

}

    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public async Task<ActionResult> Create(Flavor flavor)
    {
        var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
        var currentUser = await _userManager.FindByIdAsync(userId);
        flavor.User = currentUser;
        _db.Flavors.Add(flavor);
        _db.SaveChanges();
        return RedirectToAction("Index");
    }
    [AllowAnonymous]
    public ActionResult Details(int id)
    {
      var thisFlavor = _db.Flavors
        .Include(flavor => flavor.JoinEntities)
        .ThenInclude(join => join.Treat)
        .FirstOrDefault(flavor => flavor.FlavorId == id);
      return View(thisFlavor);
    }

    public ActionResult Edit(int id)
    {
        var thisFlavor = _db.Flavors.FirstOrDefault(flavor => flavor.FlavorId == id);
        ViewBag.TreatId = new SelectList(_db.Treats, "TreatId", "Name");
        return View(thisFlavor);
    }

    [HttpPost]
    public ActionResult Edit(Flavor flavor)
    {
      _db.Entry(flavor).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    
    public ActionResult AddTreat(int id)
    {
        var thisFlavor = _db.Flavors.FirstOrDefault(flavor => flavor.FlavorId == id);
        ViewBag.TreatId = new SelectList(_db.Treats, "TreatId", "Name");
        return View(thisFlavor);
    }
    [HttpPost]
    public ActionResult AddTreat(Flavor flavor, int TreatId)
    {
        if (TreatId != 0)
        {
          _db.FlavorTreat.Add(new FlavorTreat() { TreatId = TreatId, FlavorId = flavor.FlavorId });
          _db.SaveChanges();
        }
        return RedirectToAction("Index");
    }
   public ActionResult Delete(int id)
    {
        var thisFlavor = _db.Flavors.FirstOrDefault(flavor => flavor.FlavorId == id);
        return View(thisFlavor);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
        var thisFlavor = _db.Flavors.FirstOrDefault(flavor => flavor.FlavorId == id);
        _db.Flavors.Remove(thisFlavor);
        _db.SaveChanges();
        return RedirectToAction("Index");
    }
    [HttpPost]
    public ActionResult DeleteTreat(int joinId)
    {
        var joinEntry = _db.FlavorTreat.FirstOrDefault(entry => entry.FlavorTreatId == joinId);
        _db.FlavorTreat.Remove(joinEntry);
        _db.SaveChanges();
        return RedirectToAction("Index");
    }
    
  }
}

SweetsTreats/Views/Flavors/AddTreat.cshtml
@model SweetsTreats.Models.Flavor

@{
  Layout = "_Layout";
}

<h1>ADD TREAT</h1>

<h4>Add a Treat that has @Html.DisplayFor(model => model.Name) as a flavor:</h4>

@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.FlavorId)

    @Html.Label("Select Treat", "Select Treat:")
    @Html.DropDownList("TreatId")

    <input class = "saveicon" type="image" img src="https://raw.githubusercontent.com/GarrettHays/images/main/noun-save-5040600.png" style="width:20px;">
}

<p>@Html.ActionLink("Back to Flavors", "Index", null, null, new { @class="htmlButton"})</p>

SweetsTreats/Views/Flavors/Create.cshtml
@model SweetsTreats.Models.Flavor
@{
  Layout = "_Layout";
}

<h1>ADD FLAVOR:</h1>
@using (Html.BeginForm())
{
  <div class = "inputspacing">
  @Html.LabelFor(model => model.Name, "Name:" , new { @class="customLabel"})
  @Html.TextBoxFor(model => model.Name, new { required = "required" })
  
  <input type="image" img src="https://raw.githubusercontent.com/GarrettHays/images/main/noun-add-258794.png" class = "addicon" style="width:20px;"/>
  </div>
}

SweetsTreats/Views/Flavors/Delete.cshtml
@model SweetsTreats.Models.Flavor
@{
  Layout = "_Layout";
}

<h2>Are you sure you want to delete this Flavor?</h2>

@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)
@using (Html.BeginForm())
{
  <input type="submit" value="Delete" class="htmlButton"/>
}
@Html.ActionLink("Back to Flavors", "Index", null, null, new { @class="htmlButton"})

SweetsTreats/Views/Flavors/Details.cshtml
@model SweetsTreats.Models.Flavor;
@{
  Layout = "_Layout";
}

<h1>FLAVOR DETAILS:</h1>
<h3>@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)</h3>

  @if(@Model.JoinEntities.Count == 0)
  {
    <p>No treats come in this flavor.</p>
  }
  else
  {
    <h4>Treats with this Flavor:</h4>
    <ul>
      @foreach(var join in Model.JoinEntities)
      {
        @using (Html.BeginForm("DeleteTreat", "Flavors"))
        {
          @Html.Hidden("joinId", @join.FlavorTreatId)
          <li>@join.Treat.Name
          <input type="image" class = "flavortrashicon" img src="https://raw.githubusercontent.com/GarrettHays/images/main/noun-trash-can-2342129.png" style="width:20px;"/></li>
        }
      }
    </ul>
  }


<p>
  @Html.ActionLink("Add a Treat", "AddTreat", null, new {id = Model.FlavorId}, new { @class ="htmlButton"})
  @Html.ActionLink("Back to Flavors", "Index", null, null, new { @class ="htmlButton"})
  @Html.ActionLink("Edit Flavor", "Edit", null, new {id = Model.FlavorId }, new { @class ="htmlButton"})
  @Html.ActionLink("Delete Flavor", "Delete", null, new {id = Model.FlavorId }, new { @class ="htmlButton"})
</p>

SweetsTreats/Views/Flavors/Edit.cshtml
@model SweetsTreats.Models.Flavor
@{
  Layout = "_Layout";
}

<h1>EDIT:</h1>

<h4>Edit this Flavor: @Html.DisplayFor(model => model.Name)</h4>

@using (Html.BeginForm())
{
    <div class="inputspacing">
    @Html.HiddenFor(model => model.FlavorId)

    @Html.LabelFor(model => model.Name, "Name:" , new { @class="customLabel"})
    @Html.EditorFor(model => model.Name)

    <input class = "saveicon" type="image" img src="https://raw.githubusercontent.com/GarrettHays/images/main/noun-save-5040600.png" style="width:20px;"> <a href="@Url.Action("Delete", "Flavors",  new { id = Model.FlavorId })"><img class = "trashicon" src="https://raw.githubusercontent.com/GarrettHays/images/main/noun-trash-can-2342129.png" style="width:20px;"></a>
    </div>
}

SweetsTreats/Views/Flavors/Index.cshtml
@using SweetsTreats.Models;
@{
  Layout = "_Layout";
}

<h1>FLAVORS:</h1>

  @if (@Model.Count == 0)
  {
    <h3>No Flavors have been added yet!</h3>
  } 

<ul>
  @foreach(Flavor flavor in Model)
  {
    <li>@Html.ActionLink($"{flavor.Name}", "Details", new { id = flavor.FlavorId }) | @flavor.JoinEntities.Count Treat(s)</li>
  }
</ul>
  
<p>@Html.ActionLink("Add new flavors", "Create", null, null, new { @class="htmlButton"})</p>