SweetsTreats/Models/Treat.cs
using System.Collections.Generic;

namespace SweetsTreats.Models
{
  public class Treat
    {
        public Treat()
        {
            this.JoinEntities = new HashSet<FlavorTreat>();
        }

        public int TreatId { get; set; }
        public string Name { get; set; }
        public virtual ApplicationUser User { get; set; }
        public virtual ICollection<FlavorTreat> JoinEntities { get; set; }
    } 
}

SweetsTreats/Controllers/TreatsController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using SweetsTreats.Models;
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using System.Threading.Tasks;
using System.Security.Claims;
using System.Collections.Generic;

namespace SweetsTreats.Controllers
{
  [Authorize]
  public class TreatsController : Controller
  {
    private readonly SweetsTreatsContext _db;

    private readonly UserManager<ApplicationUser> _userManager;

    public TreatsController(UserManager<ApplicationUser> userManager, SweetsTreatsContext db)
    {
      _userManager = userManager;
      _db = db;
    }
    [AllowAnonymous] 
    public ActionResult Index()
    {

      List<Treat> model = _db.Treats.ToList();
      return View(model);
    }

    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public async Task<ActionResult> Create(Treat treat)
    {
      var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      var currentUser = await _userManager.FindByIdAsync(userId);
      treat.User = currentUser;
      _db.Treats.Add(treat);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    [AllowAnonymous]
    public ActionResult Details(int id)
    {
      var thisTreat = _db.Treats
          .Include(treat => treat.JoinEntities)
          .ThenInclude(join => join.Flavor)
          .FirstOrDefault(treat => treat.TreatId == id);
      return View(thisTreat);
    }
    public ActionResult Edit(int id)
    {
      var thisTreat = _db.Treats.FirstOrDefault(treat => treat.TreatId == id);
      return View(thisTreat);
    }

    [HttpPost]
    public ActionResult Edit(Treat treat)
    {
      _db.Entry(treat).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      var thisTreat = _db.Treats.FirstOrDefault(treat => treat.TreatId == id);
      return View(thisTreat);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisTreat = _db.Treats.FirstOrDefault(treat => treat.TreatId == id);
      _db.Treats.Remove(thisTreat);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult AddFlavor(int id)
    {
        var thisTreat = _db.Treats.FirstOrDefault(treat => treat.TreatId == id);
        ViewBag.FlavorId = new SelectList(_db.Flavors, "FlavorId", "Name");
        return View(thisTreat);
    }
    [HttpPost]
    public ActionResult AddFlavor(Treat treat, int FlavorId)
    {
        if (FlavorId != 0)
        {
          _db.FlavorTreat.Add(new FlavorTreat() { FlavorId = FlavorId, TreatId = treat.TreatId });
          _db.SaveChanges();
        }
        return RedirectToAction("Index");
    }
    [HttpPost]
    public ActionResult DeleteFlavor(int joinId)
    {
        var joinEntry = _db.FlavorTreat.FirstOrDefault(entry => entry.FlavorTreatId == joinId);
        _db.FlavorTreat.Remove(joinEntry);
        _db.SaveChanges();
        return RedirectToAction("Index");
    }
  }
}

SweetsTreats/Views/Treats/AddFlavor.cshtml
@model SweetsTreats.Models.Treat

@{
  Layout = "_Layout";
}

<h1>ADD FLAVOR:</h1>

<h4>Add a flavor that the @Html.DisplayFor(model => model.Name) treat comes in:</h4>

@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.TreatId)

    @Html.Label("Select Flavor", "Select Flavor:")
    @Html.DropDownList("FlavorId")

    <input class = "saveicon" type="image" img src="https://raw.githubusercontent.com/GarrettHays/images/main/noun-save-5040600.png" style="width:20px;">
}

<p>@Html.ActionLink("Back to Treats", "Index", null, null, new { @class="htmlButton"})</p>

SweetsTreats/Views/Treats/Create.cshtml
@model SweetsTreats.Models.Treat
@{
  Layout = "_Layout";
}

<h1>ADD TREAT:</h1>
@using (Html.BeginForm())
{
  <div class = "inputspacing">
  @Html.LabelFor(model => model.Name, "Name:" , new { @class="customLabel"})
  @Html.TextBoxFor(model => model.Name, new { required = "required" })
  
  <input type="image" img src="https://raw.githubusercontent.com/GarrettHays/images/main/noun-add-258794.png" class = "addicon" style="width:20px;"/>
  </div>
}

SweetsTreats/Views/Treats/Delete.cshtml
@model SweetsTreats.Models.Treat
@{
  Layout = "_Layout";
}

<h2>Are you sure you want to delete this Treat?</h2>

@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)
@using (Html.BeginForm())
{
  <input type="submit" value="Delete" class="htmlButton"/>
}
@Html.ActionLink("Back to Treats", "Index", null, null, new { @class="htmlButton"})

SweetsTreats/Views/Treats/Details.cshtml
@model SweetsTreats.Models.Treat;
@{
  Layout = "_Layout";
}

<h1>TREAT DETAILS:</h1>
<h3>@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)</h3>

  @if(@Model.JoinEntities.Count == 0)
  {
    <p>This Treat has no Flavors!</p>
  }
  else
  {
    <h4>Flavors this Treat comes in:</h4>
    <ul>
      @foreach(var join in Model.JoinEntities)
      {
        @using (Html.BeginForm("DeleteFlavor", "Treats"))
        {
          @Html.Hidden("joinId", @join.FlavorTreatId)
          <li>@join.Flavor.Name
          <input type="image" class = "flavortrashicon" img src="https://raw.githubusercontent.com/GarrettHays/images/main/noun-trash-can-2342129.png" style="width:20px;"/></li>
        }
      }
    </ul>
  }


<p>
  @Html.ActionLink("Add a Flavor", "AddFlavor", null, new {id = Model.TreatId}, new { @class ="htmlButton"})
  @Html.ActionLink("Back to Treats", "Index", null, null, new { @class ="htmlButton"})
  @Html.ActionLink("Edit Treat", "Edit", null, new {id = Model.TreatId }, new { @class ="htmlButton"})
  @Html.ActionLink("Delete Treat", "Delete", null, new {id = Model.TreatId }, new { @class ="htmlButton"})
</p>

SweetsTreats/Views/Treats/Edit.cshtml
@model SweetsTreats.Models.Treat
@{
  Layout = "_Layout";
}

<h1>EDIT:</h1>

<h4>Edit this Treat: @Html.DisplayFor(model => model.Name)</h4>

@using (Html.BeginForm())
{
    <div class="inputspacing">
    @Html.HiddenFor(model => model.TreatId)

    @Html.LabelFor(model => model.Name, "Name:" , new { @class="customLabel"})
    @Html.EditorFor(model => model.Name)

    <input class = "saveicon" type="image" img src="https://raw.githubusercontent.com/GarrettHays/images/main/noun-save-5040600.png" style="width:20px;"> <a href="@Url.Action("Delete", "Treats",  new { id = Model.TreatId })"><img class = "trashicon" src="https://raw.githubusercontent.com/GarrettHays/images/main/noun-trash-can-2342129.png" style="width:20px;"></a>
    </div>
}

SweetsTreats/Views/Treats/Index.cshtml
@using SweetsTreats.Models;
@{
  Layout = "_Layout";
}

<h1>TREATS:</h1>

  @if (@Model.Count == 0)
  {
    <h3>No Treats have been added yet!</h3>
  } 

<ul>
  @foreach(Treat treat in Model)
  {
    <li>@Html.ActionLink($"{treat.Name}", "Details", new { id = treat.TreatId }) | @treat.JoinEntities.Count Flavor(s)</li>
  }
</ul>
  
<p>@Html.ActionLink("Add new treats", "Create", null, null, new { @class="htmlButton"})</p>